import React,{useEffect,useMemo,useState} from 'react';
import {Modal,Pressable,ScrollView,StyleSheet,Text,TextInput,View} from 'react-native';
import AsyncStorage from '@react-native-async-storage/async-storage';
import {SafeAreaView} from 'react-native-safe-area-context';
import {StatusBar} from 'expo-status-bar';
import {recognize} from './src/recognition';

const KEY='bywise_mobile_v1';
const PURPLE='#7136e8';
const BG='#f7f2ea';
const CARD='#fffdf9';
const CATS=['Dining','Transport','Groceries','Online Food Delivery','Online Shopping','Digital Entertainment','Entertainment & Leisure','Beauty & Wellness','Pets','Luxury Goods','Electronics & Camera','Sports & Fitness','Medical & Health','Collectibles & Toys','Education','Home & Living','Clothing & Fashion','Automobile','Travel','Bills','Gifts','Household & Daily','Shopping','Finance & Investments','Other'];

export default function App(){
 const [page,setPage]=useState('home'); const [tx,setTx]=useState([]); const [input,setInput]=useState(''); const [modal,setModal]=useState(false); const [currency,setCurrency]=useState('S$'); const [budget,setBudget]=useState(0); const [ready,setReady]=useState(false);
 useEffect(()=>{(async()=>{const x=JSON.parse(await AsyncStorage.getItem(KEY)||'{}');setTx(x.tx||[]);setCurrency(x.currency||'S$');setBudget(x.budget||0);setReady(true)})()},[]);
 useEffect(()=>{if(ready)AsyncStorage.setItem(KEY,JSON.stringify({tx,currency,budget}))},[tx,currency,budget,ready]);
 const spent=useMemo(()=>tx.filter(x=>x.type==='expense').reduce((a,x)=>a+x.amount,0),[tx]);
 const income=useMemo(()=>tx.filter(x=>x.type==='income').reduce((a,x)=>a+x.amount,0),[tx]);
 function add(){const m=input.match(/(\d+(?:\.\d{1,2})?)/);if(!m)return;const amount=Number(m[1]);const description=input.replace(m[0],'').trim();const r=recognize(input);setTx(v=>[{id:Date.now(),description,amount,type:'expense',category:r?.category||'Other',date:new Date().toISOString().slice(0,10)},...v]);setInput('');setModal(false)}
 return <SafeAreaView style={s.safe}><StatusBar style="dark"/><View style={s.header}><Text style={s.logo}>BY WISE</Text><Text style={s.profile}>User</Text></View>
 <ScrollView contentContainerStyle={s.body}>{page==='home'&&<><Text style={s.hello}>Good evening, User</Text><View style={s.money}><Text style={s.moneyLabel}>Balance</Text><Text style={s.balance}>{currency}{(income-spent).toFixed(2)}</Text><View style={s.row}><Text style={s.moneySub}>Spent {currency}{spent.toFixed(2)}</Text><Text style={s.moneySub}>Income {currency}{income.toFixed(2)}</Text></View></View><Pressable style={s.quick} onPress={()=>setModal(true)}><Text style={s.quickText}>＋ Quick Record</Text></Pressable><Text style={s.section}>Recent</Text>{tx.slice(0,8).map(x=><View key={x.id} style={s.item}><View><Text style={s.itemName}>{x.description}</Text><Text style={s.itemCat}>{x.category}</Text></View><Text style={s.itemAmt}>{x.type==='income'?'+':'−'}{currency}{x.amount.toFixed(2)}</Text></View>)}</>}
 {page==='reports'&&<><Text style={s.title}>Reports</Text><View style={s.stat}><Text>Total Income</Text><Text style={s.big}>{currency}{income.toFixed(2)}</Text></View><View style={s.stat}><Text>Total Spent</Text><Text style={s.big}>{currency}{spent.toFixed(2)}</Text></View><View style={s.stat}><Text>Net Flow</Text><Text style={s.big}>{currency}{(income-spent).toFixed(2)}</Text></View></>}
 {page==='calendar'&&<><Text style={s.title}>Calendar</Text><Text style={s.muted}>History and daily records will be migrated here from the web version.</Text></>}
 {page==='settings'&&<><Text style={s.title}>Settings</Text><View style={s.stat}><Text>Currency</Text><Pressable onPress={()=>setCurrency(currency==='S$'?'RM':'S$')}><Text style={s.link}>{currency}  Tap to switch</Text></Pressable></View><View style={s.stat}><Text>Monthly Budget</Text><Text style={s.big}>{currency}{budget.toFixed(2)}</Text><Text style={s.muted}>Spent: {currency}{spent.toFixed(2)} · Remaining: {currency}{Math.max(0,budget-spent).toFixed(2)}</Text></View></>}</ScrollView>
 <View style={s.nav}>{[['home','Home'],['reports','Reports'],['calendar','Calendar'],['settings','Settings']].map(([id,label])=><Pressable key={id} onPress={()=>setPage(id)} style={[s.navBtn,page===id&&s.navActive]}><Text style={s.navText}>{label}</Text></Pressable>)}</View>
 <Modal visible={modal} transparent animationType="slide" onRequestClose={()=>setModal(false)}><View style={s.overlay}><View style={s.sheet}><View style={s.handle}/><Text style={s.sheetTitle}>Quick Record</Text><TextInput autoFocus value={input} onChangeText={setInput} placeholder="e.g. BMW 80 · fish 10 · iPhone 3000" style={s.input}/>{input.length>0&&<View style={s.detect}><Text style={s.detectLabel}>Auto Recognition</Text><Text style={s.detectCat}>{recognize(input)?.category||'Other'}</Text></View>}<Pressable style={s.save} onPress={add}><Text style={s.saveText}>Record</Text></Pressable><Pressable onPress={()=>setModal(false)}><Text style={s.cancel}>Cancel</Text></Pressable></View></View></Modal>
 </SafeAreaView>
}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:BG},header:{paddingHorizontal:22,paddingTop:8,paddingBottom:10,flexDirection:'row',justifyContent:'space-between',alignItems:'center'},logo:{fontSize:20,fontWeight:'900',letterSpacing:1.4},profile:{fontSize:14,fontWeight:'700'},body:{padding:20,paddingBottom:110},hello:{fontSize:28,fontWeight:'800',marginBottom:16},money:{backgroundColor:'#18151e',borderRadius:28,padding:24,marginBottom:14},moneyLabel:{color:'#bdb7c9',fontSize:13},balance:{color:'#fff',fontSize:40,fontWeight:'900',marginTop:8},row:{flexDirection:'row',justifyContent:'space-between',marginTop:18},moneySub:{color:'#ddd8e5',fontSize:13},quick:{backgroundColor:PURPLE,borderRadius:18,padding:18,alignItems:'center',marginBottom:24},quickText:{color:'#fff',fontWeight:'800',fontSize:16},section:{fontSize:18,fontWeight:'800',marginBottom:10},item:{backgroundColor:CARD,borderRadius:18,padding:16,marginBottom:9,flexDirection:'row',justifyContent:'space-between',alignItems:'center'},itemName:{fontSize:15,fontWeight:'750'},itemCat:{fontSize:12,color:'#8c8790',marginTop:4},itemAmt:{fontSize:15,fontWeight:'800'},title:{fontSize:30,fontWeight:'900',marginBottom:16},stat:{backgroundColor:CARD,borderRadius:20,padding:20,marginBottom:12},big:{fontSize:25,fontWeight:'900',marginTop:8},muted:{color:'#85808a',lineHeight:20},link:{color:PURPLE,fontWeight:'800',marginTop:8},nav:{position:'absolute',bottom:0,left:0,right:0,backgroundColor:CARD,padding:10,flexDirection:'row',justifyContent:'space-around',borderTopWidth:1,borderTopColor:'#eee7df'},navBtn:{paddingVertical:10,paddingHorizontal:13,borderRadius:14},navActive:{backgroundColor:'#eee6ff'},navText:{fontSize:12,fontWeight:'750'},overlay:{flex:1,backgroundColor:'rgba(0,0,0,.35)',justifyContent:'flex-end'},sheet:{backgroundColor:CARD,borderTopLeftRadius:30,borderTopRightRadius:30,padding:22,paddingBottom:35},handle:{width:40,height:4,borderRadius:4,backgroundColor:'#d6d0c9',alignSelf:'center',marginBottom:18},sheetTitle:{fontSize:24,fontWeight:'900',marginBottom:16},input:{backgroundColor:'#f2eee8',borderRadius:18,padding:17,fontSize:16,minHeight:70},detect:{marginTop:12,backgroundColor:'#f1eaff',borderRadius:16,padding:14},detectLabel:{fontSize:12,color:'#7f7390'},detectCat:{fontSize:17,fontWeight:'800',color:PURPLE,marginTop:3},save:{backgroundColor:PURPLE,borderRadius:18,padding:17,alignItems:'center',marginTop:16},saveText:{color:'#fff',fontWeight:'900',fontSize:16},cancel:{textAlign:'center',marginTop:15,color:'#777',fontWeight:'700'}});
